macos_min_version:
  - 10.14  # [osx and x86_64]
  - 12.3  # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.14  # [osx and x86_64]
  - 12.3  # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "10.14"                # [osx and x86_64]
  - "12.3"                 # [osx and arm64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk        # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk  # [osx and arm64]
