# Undefined symbols for architecture arm64:
# "std::__1::bad_function_call::~bad_function_call()"
c_compiler_version:    # [osx]
  - 17                 # [osx]
cxx_compiler_version:  # [osx]
  - 17                 # [osx]