{% set version = "2.2.4" %}

package:
  name: gdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 441eb1d1acb35238ca43a1a0a649493fc91fdcbab231d0747e9d462eea192278
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]
    - install_scripts.patch

build:
  number: 1
  run_exports:
    # make run_exports add appropriate libdal run dep, so that people including gdal as dep
    #    don't forget to include it as a run dep
    # no idea about abi compat, going with minor pin
    - {{ pin_compatible('libgdal', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - m2w64-xz  # [win]
    - setuptools
    - cmake  # [win]
    - numpy
    - libgdal {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  files:
    - extra_tests.py
    - test_data/sites.dbf
    - test_data/sites.sbn
    - test_data/sites.sbx
    - test_data/sites.shp
    - test_data/sites.shx
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
    - msarahan
