{% set version = "3.6.2" %}

package:
  name: gdal-split
  version: {{ version }}

source:
  url: https://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 35f40d2e08061b342513cdcddc2b997b3814ef8254514f0ef1e8bc7aa56cf681
build:
  number: 2
  # never be built on s390x
  skip: True  # [linux and s390x]
  skip: True  # [py<36]
  skip_compile_pyc:
    - "share/bash-completion/completions/*.py"

requirements:
  build:
    - cmake
    - pkg-config >=0.21      # [not win]
    - make                   # [not win]
    - ninja                  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - blosc
    - cfitsio
    - expat
    - freexl
    - geos
    - geotiff
    - giflib   # [not win]
    - hdf4
    - hdf5 1.12.1
    - jpeg
    - json-c   # [not win]
    - kealib
    - lerc
    - libcurl 7.88.1
    - libdeflate 1.17
    - libiconv
    - libkml
    - libnetcdf 4.8.1
    - libpng
    - libpq 12.15
    - libspatialite
    - libtiff
    - libuuid  # [linux]
    - libwebp-base
    - libxml2 2.10
    - lz4-c
    - openjpeg
    - openssl 3.0.8
    - pcre2
    - poppler
    - proj
    # qhull disabled because of https://github.com/conda-forge/qgis-feedstock/issues/284#issuecomment-1356490896
    # - qhull
    - sqlite
    - swig
    - tiledb 2.3.3
    - xerces-c
    - xz
    - zlib
    - zstd

outputs:
  - name: libgdal
    script: install_lib.sh  # [unix]
    script: install_lib.bat  # [win]
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libgdal', max_pin='x.x') }}

    requirements:
      build:
        - cmake
        # ranlib used at install time
        - {{ compiler('c') }}
        - binutils               # [linux]
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config             # [not win]
        - make                   # [unix]
        - ninja                  # [win]
        - sysroot_linux-64 2.17  # [linux and x86_64]

      host:
        - blosc
        - cfitsio
        - expat
        - freexl
        - geos
        - geotiff
        - giflib   # [not win]
        - hdf4
        - hdf5 1.12.1
        - jpeg
        - json-c   # [not win]
        - kealib
        - lerc
        - libcurl 7.88.1
        - libdeflate 1.17
        - libiconv
        - libkml
        - libnetcdf 4.8.1
        - libpng
        - libpq 12.15
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libwebp-base
        - libxml2 2.10
        - lz4-c
        - openjpeg
        - openssl 3.0.8
        - pcre2
        - poppler
        - proj
        # qhull disabled because of https://github.com/conda-forge/qgis-feedstock/issues/284#issuecomment-1356490896
        # - qhull
        - sqlite
        - tiledb 2.3.3
        - xerces-c
        - xz
        - zlib
        - zstd

      run:
        - cfitsio
        - geotiff
        - giflib   # [not win]
        - json-c   # [not win]
        - libiconv
        - libkml
        - libpq
        - libspatialite
        - libuuid  # [linux]
        - libwebp-base
        - libxml2
        - openjpeg
        - poppler
        - proj
        - qhull
        - tiledb
        - xz
        - zstd
        - openssl 3.*

    test:
      files:
        - test_data
        - run_test.bat
        - run_test.sh

    about:
      summary: The Geospatial Data Abstraction Library (GDAL)
      license: MIT
      license_family: MIT
      license_file: LICENSE.TXT

  - name: libgdal-arrow-parquet
    script: build_arrow_parquet.sh  # [unix]
    script: build_arrow_parquet.bat  # [win]
    build:
      # only for libarrow > 10
      skip: True  # [arrow_cpp != "10.0.1"]

    requirements:
      build:
        - cmake
        # ranlib used at install time
        - {{ compiler('c') }}
        - binutils               # [linux]
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config             # [not win]
        - make  # [unix]
        - ninja  # [win]
        - sysroot_linux-64 2.17  # [linux and x86_64]

      host:
        - {{ pin_subpackage('libgdal', max_pin='x.x.x', exact=True) }}
        - blosc
        - cfitsio
        - curl
        - expat
        - freexl
        - geos
        - geotiff
        - giflib   # [not win]
        - hdf4
        - hdf5 1.12.1
        - jpeg
        - json-c   # [not win]
        - kealib
        - arrow-cpp
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libwebp-base
        - libxml2 2.10
        - openjpeg
        - openssl 3.0.8
        - pcre2
        - poppler
        - postgresql
        - proj
        - qhull
        - sqlite
        - tiledb
        - xerces-c
        - xz
        - zlib
        - zstd

      run:
        - {{ pin_subpackage('libgdal', max_pin='x.x.x', exact=True) }}
        - cfitsio
        - geotiff
        - giflib   # [not win]
        - json-c   # [not win]
        - libpq
        - libspatialite
        - libuuid  # [linux]
        - libwebp-base
        - poppler
        - proj
        - tiledb
        - xz
        - zstd
        - openssl 3.*

    test:
      files:
        - test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]
      commands:
        - sh test_arrow_parquet.sh   # [unix]
        - test_arrow_parquet.bat  # [win]

    about:
      summary: Arrow and Parquet drivers for the Geospatial Data Abstraction Library (GDAL)
      license: MIT
      license_family: MIT
      license_file: LICENSE.TXT

  - name: gdal
    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]
    build:
      skip_compile_pyc:
        - share/bash-completion/completions/*.py

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make   # [unix]
        - ninja  # [win]

      host:
        - python
        - pip
        - setuptools
        - wheel
        - numpy
        - {{ pin_subpackage('libgdal', max_pin='x.x.x', exact=True) }}
        # We need to have the same versions as in the host for libgdal
        - openjpeg
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('libgdal', max_pin='x.x.x', exact=True) }}

    test:
      files:
        - test_data
        - extra_tests.py
        - run_test.py
      imports:
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
      commands:
        - python run_test.py

      about:
        summary: Python wrapper for the Geospatial Data Abstraction Library (GDAL)
        license: MIT
        license_family: MIT
        license_file: LICENSE.TXT

about:
  home: https://www.gdal.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: The Geospatial Data Abstraction Library (GDAL)
  description: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.
  dev_url: https://github.com/OSGeo/gdal
  doc_url: https://gdal.org/tutorials/index.html

extra:
  recipe-maintainers:
    - zklaus
    - akrherz
    - gillins
    - katietz
    - kmuehlbauer
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
