{% set version = "3.2.2" %}

package:
  name: gdal-split
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: a7e1e414e5c405af48982bf4724a3da64a05770254f2ce8affb5f58a7604ca57
  patches:
    # BUILT_AS_DYNAMIC_LIB.
    - patches/windowshdf5.patch  # [win]
    # Use multiple cores on Windows.  (Now enabled by upstream)
    #- patches/multiprocessor.patch  # [win]
    # disable 12 bit jpeg on Windows as we aren't using internal jpeg
    - patches/disable_jpeg12.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - m2-patch  # [win]
    - cmake  # [win]
    - pkg-config >=0.21  # [not win]
    - make  # [unix]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cfitsio
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - icu
    - jpeg
    - json-c  # [not win]
    - kealib
    - libcurl
    - libdap4  # [not win]
    - libkml
    - libnetcdf
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - libuuid  # [linux]
    - libwebp-base
    - libxml2
    - openjpeg
    - openssl
    - pcre
    - poppler # [not win]
    - postgresql
    - proj
    - sqlite
    - tiledb
    - xerces-c
    - xz
    - zlib
    - zstd

outputs:
  - name: libgdal
    script: install_lib.sh   # [unix]
    script: install_lib.bat  # [win]
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libgdal', max_pin='x.x') }}
      ignore_run_exports:
        - postgresql
        # TODO: figure out why these are being statically linked, and/or why
        # `conda-build` mis-detects them as over-depending. On OS X, at least,
        # build logs show them being passed via the linker `-l` option.
        - icu       # [osx or win]
        - libkml    # [win]
        - libxml2   # [win]
        - openssl   # [win]
        - pcre      # [win]
        - xz        # [osx or win]
        - zlib      # [osx or win]
        - zstd      # [osx or win]

    requirements:
      build:
        # ranlib used at install time
        - {{ compiler('c') }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
        - make  # [unix]
      host:
        - cfitsio
        - curl
        - expat
        - freexl
        - geos
        - geotiff
        - giflib  # [not win]
        - hdf4
        - hdf5
        - icu
        - jpeg
        - json-c  # [not win]
        - icu
        - kealib
        - libcurl
        - libdap4  # [not win]
        - libiconv  # [osx]
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libwebp-base
        - libxml2
        - openjpeg
        - openssl
        - pcre
        - poppler # [not win]
        - postgresql
        - proj
        - sqlite
        - tiledb
        - xerces-c
        - xz
        - zlib
        - zstd
      run:
        - cfitsio
        - geotiff
        - giflib  # [not win]
        - json-c  # [not win]
        - libdap4  # [not win]
        - libpq
        - libspatialite
        - libuuid  # [linux]
        - libwebp-base
        - poppler # [not win]
        - postgresql
        - proj
        - tiledb
        - xz
        - zlib
        - zstd
    test:
      files:
        - test_data
        - run_test.bat
        - run_test.sh
    about:
      summary: 'The Geospatial Data Abstraction Library (GDAL)'

  - name: gdal
    script: install_python.sh   # [unix]
    script: install_python.bat  # [win]
    build:
      ignore_run_exports:
        - openssl
        - hdf5
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake  # [win]
      host:
        - python
        - pip
        - numpy
        - {{ pin_subpackage('libgdal', exact=True) }}
        # openssl and hdf5 are dependencies from libgdal but are included here
        # as conda-build tried to use incompatible versions if they are not
        # explicitiy listed.  Ignore the run exports using ignore_run_exports.
        # see https://github.com/conda/conda-build/issues/3308
        - openssl
        - hdf5
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('libgdal', exact=True) }}
    test:
      files:
        - test_data
        - extra_tests.py
        - run_test.py
      imports:
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
      commands:
        - python run_test.py
      about:
        summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.

extra:
  recipe-maintainers:
    - gillins
    - kmuehlbauer
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
