travis:
  secure:
    BINSTAR_TOKEN: FZdehvNZ/RSgFwSqJ9ur9dDPw1ZDQqEHyLepAqT4yVrGq7djtOoE0gjRf8cPWX6eUXNNqiS3cWSSdasoe1jRlHGz+tQWg3Y0ldaSVt6Ec/26yJJ5jZyoG7k172SpX3HTYKU3YdfQ9KicJoIBFhGIrxcCJHw24q60A9V0ltsqnu+quWB8ZrOP5jkzVGLEOydggNbylSgtFkQZJaQoJtyzwwUaFIgCf7zCefVyrnYEQi40BDUrzPhL5UStbA7/eWB3nZETSlIjJXalwziaWWEUaX9CLvUdY2ziLgOTo3Qnag8qTBxfmc1/wNikIjetVekIheN2XZK/ddIPmZaysmSlMVtDoW2i60nV9oTGqEyX1WAo1478VIYsQgCVO9W/W/Mvi5u/1fhT51LeJHH8fOk4QrO32cSH6eaEI/GslgXDdDHWiQFtmFFl3BtDXfGiAI57K7FXDoOhuatBOLhTBnyo23tbI1Zw+1STxT+mLOYMUxaDHdv19NRIZQTX8GAnHcpeA5YAxXN3oHf6wGUoSXeNEQzkFfQ97OwalGLd4FuUmRO+2vAyVt//l7zNM7mRJBTzhaBsFRGpur37NTeOqETcJ6LPeBBfyx4USqmH7LIUcVEhjHxFjfP2wd7ZwZcXvx5sn/rZFus/GLh4W2yk6yDGKR2KT8ScCKwom9iCqOUHiVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
